API for categories
Learn-Write-Repeat/LWR-WebApp pull request #20
Opened 2021-08-01 14:43 UTC by sanyogchangmai

### Related Issue

Closes: #19 19

### Describe the changes you've made

Give a clear description what modifications you have made

### Type of change

What sort of change have you made:

Created a model for category and wrote the rest api for CRUD operations.

2021-08-01 20:53 UTC, dhwaj1902 requested changes

2021-08-01 20:53 UTC, dhwaj1902 commented on backend/controllers/category.js
> +  const slug = slugify(req.body.category, {
use ``req.body.name``, for that error

2021-08-02 02:57 UTC, sanyogchangmai commented on backend/controllers/category.js
> +  const slug = slugify(req.body.category, {
Ok I will do it...

2021-08-02 14:06 UTC, sanyogchangmai commented on backend/controllers/category.js
> +  const slug = slugify(req.body.category, {
Its still giving the same error, but I tried to console.log the value name and position and its giving undefined its not taking the values.
![error](https://user-images.githubusercontent.com/76730995/127874104-c6fd664a-8807-4c6b-b261-76696ea5a281.JPG)
![post](https://user-images.githubusercontent.com/76730995/127874318-cd69cc53-b64e-4394-acbd-e2a7982b7a48.JPG)

2021-08-02 17:04 UTC, dhwaj1902 commented on backend/controllers/category.js
> +  const slug = slugify(req.body.category, {
Its working fine in my system
![image](https://user-images.githubusercontent.com/57860123/127898028-34a96cb6-6cc6-4f36-8826-17adddf3526a.png)

Have you changed this?
![image](https://user-images.githubusercontent.com/57860123/127898089-9b432409-8108-40c1-b2ea-ab014c7d3e2a.png)

2021-08-03 07:58 UTC, sanyogchangmai commented on backend/controllers/category.js
> +  const slug = slugify(req.body.category, {
yes I did the same....but still I am getting the same error. Since its working fine in your system should I create a new PR withe the changes?

2021-08-03 09:15 UTC, dhwaj1902 commented on backend/controllers/category.js
> +  const slug = slugify(req.body.category, {
You can do the changes and commit it. I will merge it.

2021-08-03 18:13 UTC, merged